# SQL Server connection details
[sql_server]
server = "localhost,1433"
database = "box_office"
auth = "sql" # change to "windows" if logged in with user account uid and pwd are ignored
uid = "sa"
password = "YourStrong!Passw0rd"
trusted_connection = "yes"
encrypt ="no"
trust_server_certificate = "yes"


# Bcrypt Configs 
[auth]
admin_password_hash = "$2b$12$8USHmEH3hktZZQIXyDqQGeFktBhRFmyq2YAScka7eVRB/.URgrZ02"


# local login if server is down
[break_glass]
username = "emergency_admin"
password_hash = "[redacted]"
cookie_expiry_days = 30 # TODO: persist login
secret_key = "super-secret-session-signing-key"
