# SQL Server connection details
[sql_server]
server = "localhost,1433"
database = "box_office"
auth = "sql" # change to "windows" if logged in with user account uid and pwd are ignored
uid = "sa"
password = "YourStrong!Passw0rd"
trusted_connection = "yes"
encrypt ="no"
trust_server_certificate = "yes"

# Local unencrypted login creds
[temp_login]
temp_user = "admin"
temp_password = "1234"


# Bcrypt Configs 
[auth]
cookie_expiry_days = 30 # TODO: persist login
secret_key = "super-secret-session-signing-key"


# local login if server is down
[break_glass]
username = "emergency_admin"
password_hash = "[redacted]"
